version: "3.5"
services:
  scalardl-auditor-schema-loader-cassandra:
    image: ghcr.io/scalar-labs/scalardl-schema-loader:3.4.1
    environment:
      - SCHEMA_TYPE=auditor
    volumes:
      - ./scalardb.properties:/scalardb.properties
    command:
      - "-c"
      - "/scalardb.properties"
      - "--coordinator"
      - "--replication-factor"
      - "1"
    networks:
      - scalar-network
    restart: on-failure

  scalar-ledger-as-client:
    image: ghcr.io/scalar-labs/scalar-client:3.4.5
    container_name: "scalardl-samples-scalar-ledger-as-client-1"
    volumes:
      - ./fixture/ledger.pem:/scalar/ledger.pem
      - ./fixture/ledger-key.pem:/scalar/ledger-key.pem
    depends_on:
      - ledger-envoy
      - auditor-envoy
    environment:
      - SCALAR_DL_CLIENT_SERVER_HOST=ledger-envoy
      - SCALAR_DL_CLIENT_AUDITOR_HOST=auditor-envoy
      - SCALAR_DL_CLIENT_AUDITOR_ENABLED=true
      - SCALAR_DL_CLIENT_CERT_HOLDER_ID=ledger
      - SCALAR_DL_CLIENT_CERT_PATH=/scalar/ledger.pem
      - SCALAR_DL_CLIENT_PRIVATE_KEY_PATH=/scalar/ledger-key.pem
    networks:
      - scalar-network
    command: |
      dockerize -template client.properties.tmpl:client.properties
      -template log4j2.properties.tmpl:log4j2.properties
      ./client/bin/register-cert --config client.properties
    restart: on-failure:5

  scalar-audior-as-client:
    image: ghcr.io/scalar-labs/scalar-client:3.4.5
    container_name: "scalardl-samples-scalar-auditor-as-client-1"
    volumes:
      - ./fixture/auditor.pem:/scalar/auditor.pem
      - ./fixture/auditor-key.pem:/scalar/auditor-key.pem
    depends_on:
      - ledger-envoy
      - auditor-envoy
    environment:
      - SCALAR_DL_CLIENT_SERVER_HOST=ledger-envoy
      - SCALAR_DL_CLIENT_AUDITOR_HOST=auditor-envoy
      - SCALAR_DL_CLIENT_AUDITOR_ENABLED=true
      - SCALAR_DL_CLIENT_CERT_HOLDER_ID=auditor
      - SCALAR_DL_CLIENT_CERT_PATH=/scalar/auditor.pem
      - SCALAR_DL_CLIENT_PRIVATE_KEY_PATH=/scalar/auditor-key.pem
    networks:
      - scalar-network
    command: |
      dockerize -template client.properties.tmpl:client.properties
      -template log4j2.properties.tmpl:log4j2.properties
      ./client/bin/register-cert --config client.properties
    restart: on-failure:5

  scalar-ledger:
    environment:
      - SCALAR_DL_LEDGER_AUDITOR_ENABLED=true

  scalar-auditor:
    image: ghcr.io/scalar-labs/scalar-auditor:3.4.5
    container_name: "scalardl-samples-scalar-auditor-1"
    volumes:
      - ./fixture/auditor.pem:/scalar/auditor.pem
      - ./fixture/auditor-key.pem:/scalar/auditor-key.pem
    depends_on:
      - cassandra
    environment:
      - SCALAR_DB_CONTACT_POINTS=cassandra
      - SCALAR_DB_STORAGE=cassandra
      - SCALAR_DL_AUDITOR_LEDGER_HOST=ledger-envoy
      - SCALAR_DL_AUDITOR_CERT_PATH=/scalar/auditor.pem
      - SCALAR_DL_AUDITOR_PRIVATE_KEY_PATH=/scalar/auditor-key.pem
    networks:
      - scalar-network
    # Overriding the CMD instruction in the scalar-ledger Dockerfile to add the -wait option.
    command: |
      dockerize -template auditor.properties.tmpl:auditor.properties
      -template log4j2.properties.tmpl:log4j2.properties
      -wait tcp://cassandra:9042 -timeout 60s
      ./bin/scalar-auditor --config auditor.properties

  auditor-envoy:
    image: envoyproxy/envoy:v1.21.0
    container_name: "scalardl-samples-auditor-envoy-1"
    ports:
      - "9902:9902"
      - "40051:40051"
      - "40052:40052"
    volumes:
      - ./envoy-auditor.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - scalar-auditor
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    networks:
      - scalar-network
