version: "3.5"
services:
  scalardl-auditor-schema-loader-cassandra:
    image: ghcr.io/scalar-labs/scalardl-schema-loader:1.3.0
    command:
      - "--cassandra"
      - "-h"
      - "cassandra"
      - "-R"
      - "1"
      - "-f"
      - "auditor-schema.json"
    networks:
      - scalar-ledger
    restart: on-failure

  scalar-ledger:
    environment:
      - SCALAR_DL_LEDGER_AUDITOR_ENABLED=true

  scalar-auditor:
    image: ghcr.io/scalar-labs/scalar-auditor:3.0.0
    container_name: "scalar-samples-scalar-auditor-1"
    volumes:
      - ./fixture/auditor.pem:/scalar/auditor.pem
      - ./fixture/auditor-key.pem:/scalar/auditor-key.pem
    depends_on:
      - cassandra
    environment:
      - SCALAR_DB_CONTACT_POINTS=cassandra
      - SCALAR_DB_STORAGE=cassandra
      - SCALAR_DL_AUDITOR_CERT_PATH=/scalar/auditor.pem
      - SCALAR_DL_AUDITOR_PRIVATE_KEY_PATH=/scalar/auditor-key.pem
    networks:
      - scalar-ledger
    # Overriding the CMD instruction in the scalar-ledger Dockerfile to add the -wait option.
    command: |
      dockerize -template auditor.properties.tmpl:auditor.properties
      -template log4j.properties.tmpl:log4j.properties
      -wait tcp://cassandra:9042 -timeout 60s
      ./bin/scalar-auditor --config auditor.properties

  envoy:
    ports:
      - "40051:40051"
      - "40052:40052"
