include:
  - ../common/docker-compose-ledger.yml

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "sqlserver-1"
    environment:
      MSSQL_PID: "Express"
      SA_PASSWORD: "SqlServer22"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - scalar-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -C -U sa -P SqlServer22 -Q 'SELECT 1' || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 60
      start_period: 30s

  scalardl-ledger-schema-loader:
    image: ghcr.io/scalar-labs/scalardl-schema-loader:${SCALARDL_VERSION}
    volumes:
      - ./ledger.properties:/scalardb.properties
    depends_on:
      sqlserver:
        condition: service_healthy
    command:
      - "-c"
      - "/scalardb.properties"
      - "--coordinator"
    networks:
      - scalar-network
    restart: on-failure

  scalardl-ledger:
    image: ghcr.io/scalar-labs/scalardl-ledger:${SCALARDL_VERSION}
    # image: ghcr.io/scalar-labs/scalardl-ledger-byol:${SCALARDL_VERSION}
    container_name: "scalardl-samples-scalardl-ledger-1"
    volumes:
      - ./ledger.properties:/scalar/ledger/ledger.properties.tmpl
      - ../fixture/ledger-key.pem:/scalar/ledger-key.pem
      - ../fixture/trial-license-cert.pem:/scalar/license-cert.pem
      # If you have a commercial license key, you must use `commercial-license-cert.pem` instead of `trial-license-cert.pem`.
      # - ../fixture/commercial-license-cert.pem:/scalar/license-cert.pem
    depends_on:
      scalardl-ledger-schema-loader:
        condition: service_completed_successfully

    networks:
      - scalar-network
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=localhost:50051 && grpc_health_probe -addr=ledger-envoy:50051 || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 60
      start_period: 10s
